language: python

python:
  - "2.7"

env:
  - VERSION="8.0" ODOO_REPO="odoo/odoo"
  - VERSION="8.0" ODOO_REPO="OCA/OCB"
  - VERSION="8.0" UNIT_TEST="1"

virtualenv:
  system_site_packages: true
  
before_install:
 - sudo apt-get install unixodbc unixodbc-dev freetds-common freetds-bin freetds-dev tdsodbc python-dev

install:
  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
  - git clone https://github.com/OCA/connector -b ${VERSION} $HOME/connector

script:
  - travis_run_tests

after_success:
  coveralls
